# Generated by Django 2.2.2 on 2019-06-30 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190630_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll')),
            ],
        ),
        migrations.RemoveField(
            model_name='option',
            name='poll',
        ),
        migrations.AlterField(
            model_name='option',
            name='optionset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.OptionSet'),
        ),
    ]
