# Generated by Django 2.2.2 on 2019-06-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190630_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='optionset_constraints',
        ),
        migrations.RemoveField(
            model_name='option',
            name='optionset_requires',
        ),
        migrations.AddField(
            model_name='optionset',
            name='optionset_constraints',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='optionset',
            name='optionset_requires',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
