# Generated by Django 2.2.2 on 2019-06-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190630_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionset',
            name='input_type',
            field=models.CharField(default='radio', max_length=25),
        ),
    ]
